### PR TITLE
bank file delete - change condition for delete, close #241

### LINKED ISSUE #241: import_bank_file - can not delete imported file

### PR DESCRIPTION
**Pull request by maxhansson**

### CODE REVIEW

**Comment by qzio** [comment]
why would one need to delete a bank_file import?

**Comment by maxhansson** [comment]
If something get wrong. Eg file is including wrong dates or wrong fields separations.

**Comment by qzio** [comment]
But wouldn't we want to keep a track record of the imported files?

Or would that result in duplicate data?

**Comment by maxhansson** [comment]
It is for handling of duplicates. 
If the bank file is the basis for approved verificates removal might not be able to be made.

**Comment by qzio** [comment]
:+1:
LGTM
r=@qzio

**Pull request merged**
